### ISSUE TITLE
[Frontend Update] Custom Roadmap page.

### ISSUE THREAD

**Issue by AnhLe-Axel** [maingockien01/comp4350-team8#138]
**Describe the solution you'd like**
1. Fix alignment
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/b74f4bae-3e05-43bc-86ea-5c16effd9b9c)
2. Fix flying `None`
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/a45e123c-fce3-4b1d-b5aa-b10ced5f182e)
3. Make `course name: ...` the same font and size as other text
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/efcc2cc7-0ee7-44f8-baeb-5ba7659f20c2)
4. Give this section more space
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/84bbc8e4-7d87-415f-be5b-8c204c16e37f)
5. Make sure the courses name in `Prerequisites` does not cross the edge. (Might consider using abbreviation)
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/78ef0de0-06ac-43af-bbf5-ffad1cf660ce)
6. Fix error message not showing correct course name (`object-Object` part) (again, consider using abbreviation)
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/dc83c06f-2b56-4a61-9f98-e4494caaabef)
7. Add more space between each courses and between last row courses and the `Add` button
![image](https://github.com/maingockien01/comp4350-team8/assets/65924344/aea450fd-df1b-41b3-93aa-c6580752d1a7)

**Comment by maingockien01** [comment]
Need to fix: support opening the selected course after clicking the chip to see other courses

**Comment by maingockien01** [comment]
Show error when removing prerequisite course in roadmap

**Comment by maingockien01** [comment]
Order the course list by number
